// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CarListApp.Api.Migrations
{
    [DbContext(typeof(CarListDbContext))]
    partial class CarListDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.4");

            modelBuilder.Entity("Car", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Make")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Model")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Vin")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("Cars");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Make = "Toyota",
                            Model = "Camry",
                            Vin = 123456
                        },
                        new
                        {
                            Id = 2,
                            Make = "Honda",
                            Model = "Civic",
                            Vin = 654321
                        },
                        new
                        {
                            Id = 3,
                            Make = "Ford",
                            Model = "Mustang",
                            Vin = 789012
                        },
                        new
                        {
                            Id = 4,
                            Make = "Chevrolet",
                            Model = "Malibu",
                            Vin = 345678
                        },
                        new
                        {
                            Id = 5,
                            Make = "Nissan",
                            Model = "Altima",
                            Vin = 901234
                        },
                        new
                        {
                            Id = 6,
                            Make = "Hyundai",
                            Model = "Elantra",
                            Vin = 567890
                        },
                        new
                        {
                            Id = 7,
                            Make = "Kia",
                            Model = "Optima",
                            Vin = 234567
                        },
                        new
                        {
                            Id = 8,
                            Make = "Volkswagen",
                            Model = "Jetta",
                            Vin = 890123
                        },
                        new
                        {
                            Id = 9,
                            Make = "Subaru",
                            Model = "Impreza",
                            Vin = 456789
                        },
                        new
                        {
                            Id = 10,
                            Make = "Mazda",
                            Model = "3",
                            Vin = 123789
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
